// ==========================================
// admin.tsx
// ==========================================
import { useState, useCallback } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, TextInput, ActivityIndicator, Modal, FlatList } from 'react-native';
import { FontAwesome5 } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { router, useFocusEffect } from 'expo-router';
import { WebView } from 'react-native-webview';
const API_URL = 'https://jtt.alwaysdata.net/api';

let totpValidatedCode = '';

async function apiFetch(url, options = {}) {
    const token = await AsyncStorage.getItem('token');
    const headers = { ...options.headers };
    if (token) headers['Authorization'] = `Bearer ${token}`;
    if (totpValidatedCode) headers['x-totp'] = totpValidatedCode;
    if (!(options.body instanceof FormData)) headers['Content-Type'] = 'application/json';
    return fetch(url, { ...options, headers }).then(async r => {
        if (r.status === 403) { const d = await r.json(); if (d.requireTOTP) throw new Error('TOTP_REQUIRED'); }
        return r;
    });
}

export default function AdminScreen() {
    const [st,sst]=useState({u:0,c:0,n:0,p:0,l:0}); const [vi,svi]=useState(null); const [md,smd]=useState(null);
    const [sm,ssm]=useState(new Date().getMonth()+1); const [sy,ssy]=useState(new Date().getFullYear());
    const [shm,sshm]=useState(false); const [shy,sshy]=useState(false); const [yi,syi]=useState('');
    const [sq,ssq]=useState(''); const [sr,ssr]=useState(null); const [se,sse]=useState(''); const [sl,ssl]=useState(false);
    const [at,sat]=useState('dashboard'); const [rd,srd]=useState(false);
    const [totpVisible,setTotpVisible]=useState(false); const [totpCode,setTotpCode]=useState(''); const [totpError,setTotpError]=useState('');
    const [logs,setLogs]=useState([]); const [logsTotal,setLogsTotal]=useState(0); const [logsPage,setLogsPage]=useState(0);
    const [logType,setLogType]=useState(''); const [logStart,setLogStart]=useState(''); const [logEnd,setLogEnd]=useState('');
    const cl={bg:'#020617',cd:'#0f172a',tx:'#f1f5f9',ts:'#94a3b8',bd:'rgba(99,102,241,0.2)',ib:'rgba(255,255,255,0.05)',pr:'#6366f1',sc:'#10b981',dg:'#ef4444',wn:'#f59e0b'};
    
    useFocusEffect(useCallback(()=>{(async()=>{totpValidatedCode='';setTotpVisible(true);srd(false);try{await ls();await lv();await lm(sm,sy)}catch(e){}srd(true)})()},[]));
    
    const ls=async()=>{try{const r=await apiFetch(`${API_URL}/admin/stats`);const d=await r.json();if(d.success&&d.stats)sst({u:d.stats.users,c:d.stats.courses,n:d.stats.notes,p:d.stats.pdfs,l:d.stats.links})}catch(e){if(e.message==='TOTP_REQUIRED')setTotpVisible(true)}};
    const lv=async()=>{try{const r=await apiFetch(`${API_URL}/admin/visits`);const d=await r.json();if(d.success)svi(d)}catch(e){if(e.message==='TOTP_REQUIRED')setTotpVisible(true)}};
    const lm=async(m,y)=>{try{const r=await apiFetch(`${API_URL}/admin/visits-monthly?month=${m}&year=${y}`);const d=await r.json();if(d.success)smd(d)}catch(e){if(e.message==='TOTP_REQUIRED')setTotpVisible(true)}};
    const ll=async(p=0)=>{setLogsPage(p);const limit=20;const params=new URLSearchParams({limit,offset:p*limit});if(logType)params.append('type',logType);if(logStart)params.append('startDate',logStart);if(logEnd)params.append('endDate',logEnd);try{const r=await apiFetch(`${API_URL}/admin/logs?${params}`);const d=await r.json();if(d.success){setLogs(d.logs);setLogsTotal(d.total)}}catch(e){if(e.message==='TOTP_REQUIRED')setTotpVisible(true)}};
    const es=async()=>{if(!sq.trim())return;ssl(true);sse('');ssr(null);try{const r=await apiFetch(`${API_URL}/admin/sql`,{method:'POST',body:JSON.stringify({query:sq})});const d=await r.json();if(d.success)ssr(d);else sse(d.message)}catch(e){if(e.message==='TOTP_REQUIRED')setTotpVisible(true);else sse('Erreur de connexion.')}ssl(false)};
    
    const verifyTotp=async()=>{const code=totpCode.trim();if(!code||code.length!==6){setTotpError('Code à 6 chiffres requis.');return}try{const r=await fetch(`${API_URL}/admin/totp/verify`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${await AsyncStorage.getItem('token')}`},body:JSON.stringify({matricule:'24AD421SI',token:code})});const d=await r.json();if(d.success){totpValidatedCode=code;setTotpVisible(false);setTotpCode('');setTotpError('');ls();lv();lm(sm,sy)}else{setTotpError('Code invalide.')}}catch(e){setTotpError('Erreur de vérification.')}};
    
    const ch=md&&md.data&&!md.data.every(x=>x.count===0)?(()=>{const raw=md.data;const days=md.daysInMonth;const now=new Date();const cd2=(now.getFullYear()===sy&&now.getMonth()+1===sm)?now.getDate():days;const maxVal=Math.max(...raw.map(r=>r.count),1);const stepX=maxVal<=5?1:maxVal<=20?Math.ceil(maxVal/5):Math.ceil(maxVal/6);const fillVal=maxVal+stepX;return`<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><script src="https://cdn.jsdelivr.net/npm/chart.js"><\/script><script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"><\/script><style>body{background:#0f172a;margin:0;padding:10px;font-family:monospace}canvas{width:100%!important}</style></head><body><canvas id="chart"></canvas><script>const raw=${JSON.stringify(raw)};const days=${days};const cd=${cd2};const labels=[];const values=[];const colors=[];for(let d=1;d<=days;d++){const f=raw.find(r=>r.day===d);labels.push(d);if(d>cd){values.push(${fillVal});colors.push('rgba(16,185,129,0.6)')}else if(f&&f.count>0){values.push(f.count);colors.push('rgba(99,102,241,0.7)')}else{values.push(${fillVal});colors.push('rgba(239,68,68,0.6)')}}document.getElementById('chart').style.height=(days*24+30)+'px';new Chart(document.getElementById('chart'),{type:'bar',data:{labels,datasets:[{data:values,backgroundColor:colors,borderRadius:4,barPercentage:0.65,categoryPercentage:0.8}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},datalabels:{anchor:'center',align:'center',color:'#fff',font:{size:9,weight:'bold'},formatter:v=>v>0&&v<${fillVal}?v:''}},scales:{x:{beginAtZero:true,max:${fillVal},ticks:{color:'#94a3b8',font:{size:9},stepSize:${stepX}},grid:{color:'rgba(255,255,255,0.05)'}},y:{ticks:{color:'#94a3b8',font:{size:10},autoSkip:false},grid:{display:false}}}},plugins:[ChartDataLabels]});<\/script></body></html>`})():null;
    const months=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
    
    const handleLogout=async()=>{await AsyncStorage.removeItem('currentUser');await AsyncStorage.removeItem('token');totpValidatedCode='';router.replace('/')};
    
    if(!rd)return<View style={[ss.ct,{backgroundColor:cl.bg}]}><ActivityIndicator color={cl.pr} style={{marginTop:100}}/></View>;
    return(
        <View style={[ss.ct,{backgroundColor:cl.bg}]}>
            <Modal visible={totpVisible} transparent animationType="fade">
                <View style={ss.totpOverlay}><View style={[ss.totpCard,{backgroundColor:cl.cd,borderColor:cl.bd}]}><FontAwesome5 name="shield-alt" size={40} color={cl.pr} style={{marginBottom:12,alignSelf:'center'}}/><Text style={[ss.totpTitle,{color:cl.tx}]}>Vérification TOTP</Text><Text style={{color:cl.ts,fontSize:13,textAlign:'center',marginBottom:16}}>Entrez le code à 6 chiffres de Google Authenticator</Text><View style={[ss.totpInput,{backgroundColor:cl.ib,borderColor:cl.bd}]}><TextInput style={{flex:1,color:cl.tx,fontSize:22,fontWeight:'700',textAlign:'center',letterSpacing:8}} placeholder="000000" placeholderTextColor={cl.ts} value={totpCode} onChangeText={setTotpCode} maxLength={6} keyboardType="numeric"/></View>{totpError?<Text style={{color:cl.dg,fontSize:12,textAlign:'center',marginTop:8}}>{totpError}</Text>:null}<TouchableOpacity style={[ss.totpBtn,{backgroundColor:cl.pr}]} onPress={verifyTotp}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>Vérifier</Text></TouchableOpacity></View></View>
            </Modal>
            <View style={[ss.hd,{backgroundColor:cl.cd,borderBottomColor:cl.bd}]}>
                <TouchableOpacity onPress={handleLogout}><FontAwesome5 name="arrow-left" size={16} color={cl.pr}/></TouchableOpacity>
                <Text style={[ss.ht,{color:cl.tx}]}><FontAwesome5 name="shield-alt" size={16} color={cl.pr}/> Admin Panel</Text>
                <TouchableOpacity onPress={async()=>{await ls();await lv();await lm(sm,sy)}}><FontAwesome5 name="sync" size={16} color={cl.pr}/></TouchableOpacity>
            </View>
            <View style={ss.tb}>{['dashboard','visits','sql','logs'].map(t=>(<TouchableOpacity key={t} style={[ss.ti,at===t&&{backgroundColor:cl.pr}]} onPress={()=>{sat(t);if(t==='logs')ll(0)}}><Text style={{color:'#fff',fontWeight:'600',fontSize:12}}>{t==='visits'?'Visites':t==='sql'?'SQL':t==='logs'?'Logs':'Dashboard'}</Text></TouchableOpacity>))}</View>
            {at==='dashboard'&&(<ScrollView contentContainerStyle={ss.cn}><View style={ss.sg}><View style={[ss.sb,{borderColor:'#6366f1'}]}><Text style={[ss.sn,{color:'#818cf8'}]}>{st.u}</Text><Text style={ss.sl}>Utilisateurs</Text></View><View style={[ss.sb,{borderColor:'#10b981'}]}><Text style={[ss.sn,{color:'#34d399'}]}>{st.c}</Text><Text style={ss.sl}>Cours</Text></View><View style={[ss.sb,{borderColor:'#f59e0b'}]}><Text style={[ss.sn,{color:'#fbbf24'}]}>{st.n}</Text><Text style={ss.sl}>Notes</Text></View><View style={[ss.sb,{borderColor:'#ef4444'}]}><Text style={[ss.sn,{color:'#f87171'}]}>{st.p}</Text><Text style={ss.sl}>PDFs</Text></View><View style={[ss.sb,{borderColor:'#06b6d4'}]}><Text style={[ss.sn,{color:'#22d3ee'}]}>{st.l}</Text><Text style={ss.sl}>Liens</Text></View></View></ScrollView>)}
            {at==='visits'&&vi&&(<ScrollView contentContainerStyle={ss.cn}><View style={ss.sr}><View style={[ss.sb2,{borderColor:'#6366f1'}]}><Text style={[ss.sn,{color:'#818cf8'}]}>{vi.total}</Text><Text style={ss.sl}>Total</Text></View><View style={[ss.sb2,{borderColor:'#10b981'}]}><Text style={[ss.sn,{color:'#34d399'}]}>{vi.today}</Text><Text style={ss.sl}>Aujourd'hui</Text></View><View style={[ss.sb2,{borderColor:'#f59e0b'}]}><Text style={[ss.sn,{color:'#fbbf24'}]}>{vi.week}</Text><Text style={ss.sl}>7 jours</Text></View></View><Text style={[ss.stl,{color:cl.tx,marginTop:20}]}><FontAwesome5 name="globe" size={14} color={cl.pr}/> Plateformes</Text><View style={{flexDirection:'row',gap:14}}><View style={[ss.pc,{borderColor:'#6366f1'}]}><FontAwesome5 name="globe" size={28} color="#818cf8"/><Text style={[ss.plb,{color:cl.tx}]}>Web</Text><Text style={[ss.pn,{color:'#818cf8'}]}>{vi.platforms?.find(p=>p.platform==='web')?.count||0}</Text><View style={ss.pb}><View style={[ss.pf,{width:`${vi.total>0?((vi.platforms?.find(p=>p.platform==='web')?.count||0)/vi.total)*100:0}%`,backgroundColor:'#6366f1'}]}/></View><Text style={ss.pp}>{vi.total>0?Math.round(((vi.platforms?.find(p=>p.platform==='web')?.count||0)/vi.total)*100):0}%</Text></View><View style={[ss.pc,{borderColor:'#10b981'}]}><FontAwesome5 name="mobile-alt" size={32} color="#34d399"/><Text style={[ss.plb,{color:cl.tx}]}>Mobile</Text><Text style={[ss.pn,{color:'#34d399'}]}>{vi.platforms?.find(p=>p.platform==='mobile')?.count||0}</Text><View style={ss.pb}><View style={[ss.pf,{width:`${vi.total>0?((vi.platforms?.find(p=>p.platform==='mobile')?.count||0)/vi.total)*100:0}%`,backgroundColor:'#10b981'}]}/></View><Text style={ss.pp}>{vi.total>0?Math.round(((vi.platforms?.find(p=>p.platform==='mobile')?.count||0)/vi.total)*100):0}%</Text></View></View><Text style={[ss.stl,{color:cl.tx,marginTop:20}]}><FontAwesome5 name="calendar-alt" size={14} color={cl.pr}/> Fréquentation mensuelle</Text><View style={ss.prw}><TouchableOpacity style={[ss.pbt,{backgroundColor:cl.ib,borderColor:cl.bd}]} onPress={()=>sshm(true)}><Text style={{color:cl.tx,fontSize:15,fontWeight:'600'}}>{months[sm-1]}  <FontAwesome5 name="chevron-down" size={12} color={cl.ts}/></Text></TouchableOpacity><TouchableOpacity style={[ss.pbt,{backgroundColor:cl.ib,borderColor:cl.bd}]} onPress={()=>{syi(String(sy));sshy(true)}}><Text style={{color:cl.tx,fontSize:15,fontWeight:'600'}}>{sy}  <FontAwesome5 name="chevron-down" size={12} color={cl.ts}/></Text></TouchableOpacity></View>{md&&md.data&&md.data.every(x=>x.count===0)?(<View style={[ss.em,{backgroundColor:cl.cd,borderColor:cl.bd}]}><FontAwesome5 name="info-circle" size={36} color={cl.ts} style={{marginBottom:10}}/><Text style={{color:cl.ts,fontSize:14}}>Aucune donnée pour ce mois.</Text></View>):ch?(<WebView source={{html:ch}} style={{height:Math.max(300,(md?.daysInMonth||30)*26+30)}} scrollEnabled={false} originWhitelist={['*']} javaScriptEnabled/>):null}</ScrollView>)}
            <Modal visible={shm} transparent animationType="fade"><TouchableOpacity style={ss.mo} activeOpacity={1} onPress={()=>sshm(false)}><View style={[ss.mc,{backgroundColor:cl.cd,borderColor:cl.bd}]}><FlatList data={months} keyExtractor={(_,i)=>String(i)} style={{maxHeight:300}} renderItem={({item,index})=>(<TouchableOpacity style={[ss.mi,sm===index+1&&{backgroundColor:cl.pr}]} onPress={()=>{ssm(index+1);sshm(false);lm(index+1,sy)}}><Text style={[ss.mit,sm===index+1&&{color:'#fff',fontWeight:'700'}]}>{item}</Text></TouchableOpacity>)}/></View></TouchableOpacity></Modal>
            <Modal visible={shy} transparent animationType="fade"><TouchableOpacity style={ss.mo} activeOpacity={1} onPress={()=>sshy(false)}><View style={[ss.mc,{backgroundColor:cl.cd,borderColor:cl.bd}]}><TextInput style={[ss.yi,{backgroundColor:cl.ib,borderColor:cl.bd,color:cl.tx}]} placeholder="Saisir l'année" placeholderTextColor={cl.ts} value={yi} onChangeText={syi} keyboardType="numeric" maxLength={4} onSubmitEditing={()=>{const y=parseInt(yi);if(y&&y>=2000&&y<=2100){ssy(y);sshy(false);lm(sm,y)}}}/><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12}}>{[2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030].map(y=>(<TouchableOpacity key={y} style={[ss.yc,sy===y&&{backgroundColor:cl.pr}]} onPress={()=>{ssy(y);sshy(false);lm(sm,y)}}><Text style={[ss.yct,sy===y&&{color:'#fff',fontWeight:'700'}]}>{y}</Text></TouchableOpacity>))}</View></View></TouchableOpacity></Modal>
            {at==='sql'&&(<ScrollView contentContainerStyle={ss.cn}><TextInput style={[ss.qi,{backgroundColor:cl.ib,borderColor:cl.bd,color:cl.tx}]} placeholder="SELECT * FROM users..." placeholderTextColor={cl.ts} value={sq} onChangeText={v=>{ssq(v);if(v.trim()===''){ssr(null);sse('')}}} multiline textAlignVertical="top"/><View style={{flexDirection:'row',gap:10}}><TouchableOpacity style={[ss.qb,{flex:1,backgroundColor:cl.pr}]} onPress={es} disabled={sl}>{sl?<ActivityIndicator color="#fff"/>:<Text style={{color:'#fff',fontWeight:'600'}}><FontAwesome5 name="play" size={12} color="#fff"/> Exécuter</Text>}</TouchableOpacity><TouchableOpacity style={[ss.qb,{backgroundColor:cl.ib,borderWidth:1,borderColor:cl.bd}]} onPress={()=>{ssq('');ssr(null);sse('')}}><Text style={{color:cl.ts,fontWeight:'600'}}><FontAwesome5 name="broom" size={12} color={cl.ts}/> Nettoyer</Text></TouchableOpacity></View>{se?<Text style={{color:cl.dg,marginTop:10}}>{se}</Text>:null}{sr?.data&&(<View style={{marginTop:10}}><Text style={{color:cl.sc,marginBottom:8}}><FontAwesome5 name="check-circle" size={12} color={cl.sc}/> {sr.data.length} résultat(s)</Text><ScrollView horizontal><View>{sr.data.slice(0,30).map((row,i)=>(<Text key={i} style={{color:cl.tx,fontSize:11,marginBottom:4,fontFamily:'monospace'}}>{JSON.stringify(row)}</Text>))}</View></ScrollView></View>)}</ScrollView>)}
            {at==='logs'&&(<ScrollView contentContainerStyle={ss.cn}><View style={{flexDirection:'row',gap:8,flexWrap:'wrap',marginBottom:12}}><View style={[ss.logFilter,{backgroundColor:cl.ib,borderColor:cl.bd}]}><FontAwesome5 name="tag" size={12} color={cl.ts} style={{marginRight:6}}/><TextInput style={{flex:1,color:cl.tx,fontSize:12}} placeholder="Type" placeholderTextColor={cl.ts} value={logType} onChangeText={setLogType} onSubmitEditing={()=>ll(0)}/></View><View style={[ss.logFilter,{backgroundColor:cl.ib,borderColor:cl.bd}]}><FontAwesome5 name="calendar" size={12} color={cl.ts} style={{marginRight:6}}/><TextInput style={{flex:1,color:cl.tx,fontSize:12}} placeholder="Début (YYYY-MM-DD)" placeholderTextColor={cl.ts} value={logStart} onChangeText={setLogStart} onSubmitEditing={()=>ll(0)}/></View><View style={[ss.logFilter,{backgroundColor:cl.ib,borderColor:cl.bd}]}><FontAwesome5 name="calendar" size={12} color={cl.ts} style={{marginRight:6}}/><TextInput style={{flex:1,color:cl.tx,fontSize:12}} placeholder="Fin (YYYY-MM-DD)" placeholderTextColor={cl.ts} value={logEnd} onChangeText={setLogEnd} onSubmitEditing={()=>ll(0)}/></View><TouchableOpacity style={[ss.logBtn,{backgroundColor:cl.pr}]} onPress={()=>ll(0)}><FontAwesome5 name="search" size={12} color="#fff"/></TouchableOpacity><TouchableOpacity style={[ss.logBtn,{backgroundColor:cl.ib,borderColor:cl.bd}]} onPress={()=>{setLogType('');setLogStart('');setLogEnd('');ll(0)}}><FontAwesome5 name="broom" size={12} color={cl.ts}/></TouchableOpacity></View><Text style={{color:cl.ts,fontSize:12,marginBottom:8}}><FontAwesome5 name="list" size={12} color={cl.ts}/> {logsTotal} log(s)</Text>{logs.length===0?<View style={[ss.em,{backgroundColor:cl.cd,borderColor:cl.bd}]}><FontAwesome5 name="inbox" size={40} color={cl.ts} style={{marginBottom:8}}/><Text style={{color:cl.ts}}>Aucun log</Text></View>:logs.map((log,i)=>(<View key={i} style={[ss.logItem,{backgroundColor:cl.cd,borderColor:cl.bd}]}><View style={{flex:1}}><Text style={{color:cl.tx,fontSize:12,fontWeight:'600'}}>{log.type}</Text><Text style={{color:cl.ts,fontSize:10}}>{new Date(log.created_at).toLocaleString('fr-FR')}</Text><Text style={{color:cl.ts,fontSize:10}}>{log.user_name||'Anonyme'} • {log.ip_address||'-'}</Text>{log.details?<Text style={{color:cl.ts,fontSize:10}} numberOfLines={1}>{log.details}</Text>:null}</View></View>))}{logsTotal>20&&(<View style={{flexDirection:'row',justifyContent:'center',gap:6,marginTop:12}}>{Array.from({length:Math.ceil(logsTotal/20)},(_,i)=>(<TouchableOpacity key={i} style={[ss.pageBtn,i===logsPage&&{backgroundColor:cl.pr}]} onPress={()=>ll(i)}><Text style={{color:i===logsPage?'#fff':cl.ts,fontSize:12,fontWeight:'600'}}>{i+1}</Text></TouchableOpacity>))}</View>)}</ScrollView>)}
        </View>
    );
}
const ss=StyleSheet.create({
    ct:{flex:1},hd:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:14,paddingTop:50,borderBottomWidth:1},ht:{fontSize:18,fontWeight:'700'},
    tb:{flexDirection:'row',padding:8,gap:4},ti:{flex:1,paddingVertical:10,borderRadius:8,alignItems:'center'},cn:{padding:16},
    sg:{flexDirection:'row',flexWrap:'wrap',gap:10},sr:{flexDirection:'row',gap:10,marginBottom:4},
    sb:{width:'30%',borderRadius:16,padding:16,alignItems:'center',borderWidth:2,backgroundColor:'#0f172a'},sb2:{flex:1,borderRadius:16,padding:16,alignItems:'center',borderWidth:2,backgroundColor:'#0f172a'},
    sn:{fontSize:24,fontWeight:'800'},sl:{color:'#94a3b8',fontSize:11,marginTop:4,textTransform:'uppercase',fontWeight:'600'},
    stl:{fontSize:15,fontWeight:'700',marginBottom:12},pc:{flex:1,backgroundColor:'#0f172a',borderRadius:16,padding:16,alignItems:'center',borderWidth:2},
    plb:{fontWeight:'700',fontSize:13,marginTop:6},pn:{fontWeight:'800',fontSize:26,marginTop:4},
    pb:{width:'100%',height:6,backgroundColor:'rgba(255,255,255,0.1)',borderRadius:3,marginTop:8,overflow:'hidden'},pf:{height:'100%',borderRadius:3},pp:{color:'#94a3b8',fontSize:10,marginTop:4},
    prw:{flexDirection:'row',gap:12,marginBottom:12},pbt:{flex:1,borderRadius:12,borderWidth:1,padding:14,alignItems:'center'},
    em:{alignItems:'center',padding:30,borderRadius:16,borderWidth:1},
    mo:{flex:1,backgroundColor:'rgba(0,0,0,0.6)',justifyContent:'center',alignItems:'center',padding:20},mc:{width:'80%',borderRadius:16,padding:16,borderWidth:1,maxHeight:400},
    mi:{padding:14,borderRadius:10,marginBottom:4},mit:{color:'#94a3b8',fontSize:15,textAlign:'center'},
    yi:{borderWidth:1,borderRadius:10,padding:12,fontSize:16,textAlign:'center',marginBottom:8},yc:{paddingHorizontal:14,paddingVertical:10,borderRadius:10,backgroundColor:'rgba(255,255,255,0.05)'},yct:{color:'#94a3b8',fontSize:14},
    qi:{borderWidth:2,borderRadius:12,padding:14,fontSize:13,fontFamily:'monospace',minHeight:100,marginBottom:10},qb:{padding:14,borderRadius:12,alignItems:'center'},
    totpOverlay:{flex:1,backgroundColor:'rgba(0,0,0,0.8)',justifyContent:'center',alignItems:'center',padding:30},
    totpCard:{width:'100%',maxWidth:360,borderRadius:20,padding:24,borderWidth:1},
    totpTitle:{fontSize:18,fontWeight:'700',textAlign:'center',marginBottom:4},
    totpInput:{borderWidth:2,borderRadius:14,padding:12,alignItems:'center'},
    totpBtn:{borderRadius:14,padding:14,alignItems:'center',marginTop:14},
    logFilter:{flexDirection:'row',alignItems:'center',borderWidth:1,borderRadius:10,paddingHorizontal:10,height:38,flex:1,minWidth:100},
    logBtn:{width:38,height:38,borderRadius:10,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:'transparent'},
    logItem:{padding:10,borderRadius:10,marginBottom:6,borderWidth:1},
    pageBtn:{width:32,height:32,borderRadius:8,justifyContent:'center',alignItems:'center',backgroundColor:'rgba(255,255,255,0.05)'},
});