import { useState, useEffect, useCallback } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, TextInput, Alert, Modal, Linking } from 'react-native';
import { Image } from 'expo-image';
import { FontAwesome5 } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { router, useFocusEffect } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system/legacy';

const API_URL = 'https://jtt.alwaysdata.net/api';
const CL_URL = 'https://api.cloudinary.com/v1_1/dfosclwrp/image/upload';
const CL_UP = 'genotApp';

export default function SettingsScreen() {
    const [u,su] = useState(null); const [st,sst] = useState({c:0,n:0,p:0,l:0}); const [on,son] = useState(false); const [th,sth] = useState('dark');
    const [em,sem] = useState(false); const [et,set] = useState(''); const [ev,sev] = useState(''); const [di,sdi] = useState(0);
    const dim = [require('../../assets/images/dev1.jpg'),require('../../assets/images/dev2.jpg'),require('../../assets/images/dev3.jpg'),require('../../assets/images/dev4.jpg'),require('../../assets/images/dev5.jpg'),require('../../assets/images/dev6.jpg')];
    useEffect(()=>{AsyncStorage.getItem('theme').then(t=>{if(t)sth(t)});const iv=setInterval(()=>{sdi(p=>(p+1)%dim.length)},4000);return()=>clearInterval(iv);},[]);
    const dk=th==='dark';const cl={bg:dk?'#020617':'#f0f2f5',cd:dk?'#0f172a':'#ffffff',ca:dk?'#1a1a2e':'#f8fafc',tx:dk?'#f1f5f9':'#1a1a2e',ts:dk?'#94a3b8':'#64748b',bd:dk?'rgba(99,102,241,0.2)':'#e2e8f0',ib:dk?'rgba(255,255,255,0.05)':'#f8fafc',pr:'#6366f1',pl:'#818cf8',sc:'#10b981',dg:'#ef4444',wn:'#f59e0b'};
    useFocusEffect(useCallback(()=>{(async()=>{const uu=await AsyncStorage.getItem('currentUser');if(!uu){router.replace('/');return}const ud=JSON.parse(uu);su(ud);(async()=>{try{const r=await fetch(`${API_URL}/ping`);son((await r.json()).success)}catch(e){son(false)}})();(async(mat)=>{try{const r=await fetch(`${API_URL}/courses/${mat}`);const d=await r.json();if(d.success){const ns=d.allNotes||[];sst({c:d.courses.length,n:ns.filter(x=>x.type==='note').length,p:ns.filter(x=>x.type==='support').length,l:ns.filter(x=>x.type==='link').length})}}catch(e){}})(ud.matricule)})()},[]));
    const lo=async()=>{await AsyncStorage.removeItem('currentUser');router.replace('/')};
    const oe=(t,v)=>{set(t);sev(v||'');sem(true)};
    const se=async()=>{try{const r=await fetch(`${API_URL}/update-profile/${u.matricule}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({[et]:ev})});const d=await r.json();if(d.success){su(d.user);await AsyncStorage.setItem('currentUser',JSON.stringify(d.user))}else Alert.alert('Erreur',d.message)}catch(e){Alert.alert('Erreur','Impossible de modifier.')}sem(false)};
    const pi=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:0.7});if(!r.canceled){try{const b64=await FileSystem.readAsStringAsync(r.assets[0].uri,{encoding:FileSystem.EncodingType.Base64});const fd=new FormData();fd.append('file',`data:image/jpeg;base64,${b64}`);fd.append('upload_preset',CL_UP);fd.append('folder','profiles');const cr=await fetch(CL_URL,{method:'POST',body:fd});const cd=await cr.json();if(cd.secure_url){const rr=await fetch(`${API_URL}/update-profile/${u.matricule}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({photo:cd.secure_url})});const dd=await rr.json();if(dd.success){const up={...u,photo:cd.secure_url};su(up);await AsyncStorage.setItem('currentUser',JSON.stringify(up))}else Alert.alert('Erreur',dd.message)}else Alert.alert('Erreur','Échec upload')}catch(e){Alert.alert('Erreur','Impossible upload')}}};
    if(!u)return<View style={[ss.ct,{backgroundColor:cl.bg}]}><Text style={{color:cl.tx,textAlign:'center',marginTop:100}}>Chargement...</Text></View>;
    return(
        <View style={[ss.ct,{backgroundColor:cl.bg}]}>
            <View style={[ss.hd,{backgroundColor:cl.cd,borderBottomColor:cl.bd}]}><TouchableOpacity onPress={()=>router.back()} style={ss.hb}><FontAwesome5 name="arrow-left" size={18} color={cl.pr}/></TouchableOpacity><Text style={[ss.ht,{color:cl.tx}]}>Paramètres</Text><View style={ss.hb}/></View>
            <ScrollView contentContainerStyle={ss.cn} showsVerticalScrollIndicator={false}>
                <View style={[ss.sc,{backgroundColor:cl.cd,borderColor:cl.bd}]}>
                    <TouchableOpacity onPress={pi} style={ss.ac}>{u.photo?<Image source={{uri:u.photo}} style={ss.av} contentFit="cover" transition={200} cachePolicy="memory-disk"/>:<View style={ss.ap}><FontAwesome5 name="user" size={60} color="#fff"/></View>}<View style={ss.ab}><FontAwesome5 name="camera" size={14} color="#fff"/></View></TouchableOpacity>
                    <Text style={[ss.un,{color:cl.tx}]}>{u.nom||'---'}</Text><Text style={[ss.um,{color:cl.ts}]}>{u.matricule}</Text>
                    <View style={ss.ig}>
                        <TouchableOpacity style={[ss.ii,{backgroundColor:cl.ca,borderColor:cl.bd}]} onPress={()=>oe('nom',u.nom)}><FontAwesome5 name="user" size={14} color={cl.pl}/><Text style={[ss.iv,{color:cl.tx}]} numberOfLines={1}>{u.nom||'---'}</Text><FontAwesome5 name="pen" size={10} color={cl.ts}/></TouchableOpacity>
                        <View style={[ss.ii,{backgroundColor:cl.ca,borderColor:cl.bd}]}><FontAwesome5 name="id-card" size={14} color={cl.pl}/><Text style={[ss.iv,{color:cl.tx}]}>{u.matricule}</Text></View>
                        <TouchableOpacity style={[ss.ii,{backgroundColor:cl.ca,borderColor:cl.bd}]} onPress={()=>oe('email',u.email)}><FontAwesome5 name="envelope" size={14} color={cl.pl}/><Text style={[ss.iv,{color:cl.tx}]} numberOfLines={1}>{u.email||'Non renseigné'}</Text><FontAwesome5 name="pen" size={10} color={cl.ts}/></TouchableOpacity>
                        <View style={[ss.ii,{backgroundColor:cl.ca,borderColor:cl.bd}]}><FontAwesome5 name="palette" size={14} color={cl.pl}/><Text style={[ss.iv,{color:cl.tx}]}>{dk?'🌙 Sombre':'☀️ Clair'}</Text></View>
                    </View>
                    <Text style={[ss.stl,{color:cl.pl}]}><FontAwesome5 name="chart-bar" size={14} color={cl.pl}/> Statistiques</Text>
                    <View style={ss.sg}>
                        <Sbx i="book" v={st.c} l="Cours" c={cl}/><Sbx i="sticky-note" v={st.n} l="Notes" c={cl}/><Sbx i="file-pdf" v={st.p} l="PDFs" c={cl}/><Sbx i="link" v={st.l} l="Liens" c={cl}/>
                    </View>
                    <View style={[ss.cb,{backgroundColor:on?'rgba(16,185,129,0.1)':'rgba(239,68,68,0.1)',borderColor:on?'rgba(16,185,129,0.3)':'rgba(239,68,68,0.3)'}]}><FontAwesome5 name="wifi" size={14} color={on?cl.sc:cl.dg}/><Text style={{color:on?cl.sc:cl.dg,fontSize:13,fontWeight:'500',flex:1,marginLeft:10}}>{on?'Connecté à Internet':'Pas de connexion'}</Text><View style={[ss.sd,{backgroundColor:on?cl.sc:cl.dg}]}/></View>
                </View>
                <View style={[ss.sc,{backgroundColor:cl.cd,borderColor:cl.bd}]}><Text style={[ss.sh,{color:cl.tx}]}><FontAwesome5 name="info-circle" size={16} color={cl.pl}/> À propos de GeNot</Text><Text style={[ss.ad,{color:cl.ts}]}>Plateforme de gestion des notes de cours conçue pour les étudiants. Centralisez vos cours, notes, supports PDF et liens utiles en un seul endroit. Ne perdez plus jamais vos précieuses ressources académiques !</Text><View style={ss.fl}>{[['Gestion des cours'],['Notes organisées'],['Supports PDF'],['Liens utiles'],['Corbeille sécurisée'],['Mode sombre/clair']].map(([t],i)=><View key={i} style={{flexDirection:'row',alignItems:'center',gap:8,marginBottom:6}}><FontAwesome5 name="check-circle" size={12} color={cl.sc}/><Text style={{color:cl.ts,fontSize:13}}>{t}</Text></View>)}</View></View>
                <View style={[ss.sc,{backgroundColor:cl.cd,borderColor:cl.bd}]}><Text style={[ss.sh,{color:cl.tx}]}><FontAwesome5 name="code" size={16} color={cl.pl}/> Développeur</Text><View style={ss.dh}><Image source={dim[di]} style={ss.da} contentFit="cover" transition={600}/><Text style={[ss.dn,{color:cl.tx}]}>Jean TSHIKAKU</Text><Text style={[ss.dr,{color:cl.pl}]}>Développeur Junior & Étudiant</Text></View><Text style={[ss.db,{color:cl.ts}]}>Passionné par la technologie et l'innovation, je crée des solutions numériques pour faciliter la vie des étudiants. Ce projet est né de mon propre besoin d'organiser mes notes de cours.</Text><Text style={[ss.ch,{color:cl.tx}]}>Me contacter</Text>
                <TouchableOpacity style={[ss.ccd,{backgroundColor:cl.ca,borderColor:cl.bd}]} onPress={()=>Linking.openURL('https://wa.me/243832976093')}><View style={[ss.ciw,{backgroundColor:'rgba(37,211,102,0.15)'}]}><FontAwesome5 name="whatsapp" size={20} color="#25d366"/></View><View style={{flex:1}}><Text style={[ss.clb,{color:cl.ts}]}>WhatsApp</Text><Text style={[ss.cvl,{color:cl.tx}]}>+243 83 29 760 93</Text></View><FontAwesome5 name="external-link-alt" size={12} color={cl.ts}/></TouchableOpacity>
                <TouchableOpacity style={[ss.ccd,{backgroundColor:cl.ca,borderColor:cl.bd}]} onPress={()=>Linking.openURL('tel:+243999543276')}><View style={[ss.cip,{backgroundColor:'rgba(99,102,241,0.15)'}]}><FontAwesome5 name="phone-alt" size={18} color={cl.pr}/></View><View style={{flex:1}}><Text style={[ss.clb,{color:cl.ts}]}>Appel</Text><Text style={[ss.cvl,{color:cl.tx}]}>+243 99 95 432 76</Text></View><FontAwesome5 name="external-link-alt" size={12} color={cl.ts}/></TouchableOpacity>
                <TouchableOpacity style={[ss.ccd,{backgroundColor:cl.ca,borderColor:cl.bd}]} onPress={()=>Linking.openURL('mailto:jtshikaku@gmail.com')}><View style={[ss.cie,{backgroundColor:'rgba(239,68,68,0.15)'}]}><FontAwesome5 name="envelope" size={18} color={cl.dg}/></View><View style={{flex:1}}><Text style={[ss.clb,{color:cl.ts}]}>Email</Text><Text style={[ss.cvl,{color:cl.tx}]}>jtshikaku@gmail.com</Text></View><FontAwesome5 name="external-link-alt" size={12} color={cl.ts}/></TouchableOpacity>
                <Text style={[ss.cp,{color:cl.ts}]}>© 2026 Jean TSHIKAKU. Tous droits réservés.</Text></View>
                <TouchableOpacity style={ss.lb} onPress={lo}><FontAwesome5 name="sign-out-alt" size={16} color="#f87171"/><Text style={ss.lt}> Se déconnecter</Text></TouchableOpacity>
            </ScrollView>
            <Modal visible={em} transparent animationType="fade"><View style={ss.mo}><View style={[ss.mc,{backgroundColor:cl.cd,borderColor:cl.bd}]}><Text style={[ss.mt,{color:cl.tx}]}>Modifier {et==='nom'?'le nom':"l'email"}</Text><TextInput style={[ss.mi,{backgroundColor:cl.ib,borderColor:cl.bd,color:cl.tx}]} value={ev} onChangeText={sev} placeholder={et==='nom'?'Nouveau nom':'Nouvel email'} placeholderTextColor={cl.ts}/><View style={ss.ma}><TouchableOpacity style={[ss.mb,{backgroundColor:cl.ib}]} onPress={()=>sem(false)}><Text style={{color:cl.tx,fontWeight:'600'}}>Annuler</Text></TouchableOpacity><TouchableOpacity style={[ss.mb,{backgroundColor:cl.pr}]} onPress={se}><Text style={{color:'#fff',fontWeight:'600'}}>Enregistrer</Text></TouchableOpacity></View></View></View></Modal>
        </View>
    );
}

const Sbx=({i,v,l,c})=><View style={[bx.bo,{backgroundColor:c.ca,borderColor:c.bd}]}><FontAwesome5 name={i} size={18} color={c.pl} style={{marginBottom:6}}/><Text style={[bx.va,{color:c.tx}]}>{v}</Text><Text style={[bx.la,{color:c.ts}]}>{l}</Text></View>;
const bx=StyleSheet.create({bo:{flex:1,borderRadius:14,padding:14,alignItems:'center',borderWidth:1},va:{fontSize:22,fontWeight:'800'},la:{fontSize:11,marginTop:2,fontWeight:'500'}});
const ss=StyleSheet.create({
    ct:{flex:1},hd:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,paddingTop:50,paddingBottom:14,borderBottomWidth:1},hb:{width:40,height:40,justifyContent:'center',alignItems:'center'},ht:{fontSize:18,fontWeight:'700'},cn:{padding:16,paddingBottom:40},
    sc:{borderRadius:20,padding:20,marginBottom:16,borderWidth:1},ac:{alignSelf:'center',marginBottom:16,position:'relative'},av:{width:150,height:150,borderRadius:75,borderWidth:4,borderColor:'#6366f1'},ap:{width:150,height:150,borderRadius:75,backgroundColor:'#6366f1',justifyContent:'center',alignItems:'center'},
    ab:{position:'absolute',bottom:6,right:6,width:38,height:38,borderRadius:19,backgroundColor:'#6366f1',justifyContent:'center',alignItems:'center',borderWidth:3,borderColor:'#fff'},un:{fontSize:22,fontWeight:'700',textAlign:'center',marginBottom:4},um:{fontSize:14,textAlign:'center',marginBottom:20},
    ig:{gap:8,marginBottom:20},ii:{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:12,borderWidth:1},iv:{flex:1,fontSize:13},stl:{fontSize:15,fontWeight:'700',marginBottom:12},sg:{flexDirection:'row',gap:8,marginBottom:16},
    cb:{flexDirection:'row',alignItems:'center',padding:12,borderRadius:12,borderWidth:1},sd:{width:8,height:8,borderRadius:4},sh:{fontSize:16,fontWeight:'700',marginBottom:14},ad:{fontSize:13,lineHeight:20,marginBottom:16},fl:{gap:2},
    dh:{alignItems:'center',marginBottom:16},da:{width:160,height:160,borderRadius:80,borderWidth:4,borderColor:'#6366f1',marginBottom:14},dn:{fontSize:20,fontWeight:'700',marginBottom:4,textAlign:'center'},dr:{fontSize:14,fontWeight:'500',textAlign:'center'},
    db:{fontSize:13,lineHeight:20,marginBottom:18,textAlign:'center'},ch:{fontSize:14,fontWeight:'700',marginBottom:10},ccd:{flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:14,marginBottom:8,borderWidth:1},
    ciw:{width:42,height:42,borderRadius:21,justifyContent:'center',alignItems:'center'},cip:{width:42,height:42,borderRadius:21,justifyContent:'center',alignItems:'center'},cie:{width:42,height:42,borderRadius:21,justifyContent:'center',alignItems:'center'},
    clb:{fontSize:10,textTransform:'uppercase',letterSpacing:0.5,marginBottom:2},cvl:{fontSize:13,fontWeight:'600'},cp:{fontSize:11,textAlign:'center',marginTop:14},
    lb:{flexDirection:'row',backgroundColor:'rgba(239,68,68,0.1)',borderRadius:50,padding:16,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(239,68,68,0.2)'},lt:{color:'#f87171',fontSize:15,fontWeight:'600'},
    mo:{flex:1,backgroundColor:'rgba(0,0,0,0.6)',justifyContent:'center',alignItems:'center',padding:20},mc:{width:'100%',borderRadius:20,padding:24,borderWidth:1},mt:{fontSize:17,fontWeight:'700',marginBottom:16,textAlign:'center'},
    mi:{borderWidth:2,borderRadius:12,padding:14,fontSize:15,marginBottom:16},ma:{flexDirection:'row',gap:10},mb:{flex:1,padding:14,borderRadius:12,alignItems:'center'},
});